In [10]:
import numpy as np
from ase.io import read

In [12]:
repeat = [4,4,4]
ru = read("./Ru.cif").repeat(repe
at)

NameError: name 'reat' is not defined

In [6]:
tmp

array([[0.1822265 , 0.3819185 , 0.23973174],
       [0.21267105, 0.98324275, 0.35613692],
       [0.45291803, 0.59582492, 0.16160655],
       [0.66209791, 0.68692153, 0.53116203],
       [0.56372841, 0.34217198, 0.23899792],
       [0.69435971, 0.08756639, 0.09559222],
       [0.94176559, 0.14316992, 0.79852988]])

In [8]:
tmp * [1,2,3]

array([[0.1822265 , 0.763837  , 0.71919522],
       [0.21267105, 1.9664855 , 1.06841077],
       [0.45291803, 1.19164985, 0.48481965],
       [0.66209791, 1.37384307, 1.59348609],
       [0.56372841, 0.68434397, 0.71699377],
       [0.69435971, 0.17513277, 0.28677666],
       [0.94176559, 0.28633984, 2.39558965]])

In [9]:
tmp * np.array([1,2,3])

array([[0.1822265 , 0.763837  , 0.71919522],
       [0.21267105, 1.9664855 , 1.06841077],
       [0.45291803, 1.19164985, 0.48481965],
       [0.66209791, 1.37384307, 1.59348609],
       [0.56372841, 0.68434397, 0.71699377],
       [0.69435971, 0.17513277, 0.28677666],
       [0.94176559, 0.28633984, 2.39558965]])